"""Ko'p tilli matnlar: UZ / RU / EN — bot asosan T() orqali."""

CURRENCIES = ['UZS', 'USD', 'RUB']
CURRENCY_SYMBOLS = {'UZS': "so'm", 'USD': '$', 'RUB': '₽'}
CATEGORIES = ['Mahsulot', 'Xizmat', 'Shaxsiy', 'Boshqa']

_KEYS = {
    'uz': {
        'lang_changed': "✅ Til: O'zbek 🇺🇿",
        'no_debts': "📭 Hozircha faol qarzlar yo'q!",
        'cancelled': "↩️ Bekor qilindi.",
        'enter_name': "👤 Qarzdorning <b>ismini</b> yozing:",
        'enter_amount': "💰 <b>Summasini</b> yozing:",
        'enter_currency': "💱 <b>Valyutani</b> tanlang:",
        'enter_category': "🗂 <b>Kategoriyani</b> tanlang:",
        'enter_due': "📅 <b>Muddat</b> kiriting (ixtiyoriy):",
        'enter_note': "📝 <b>Izoh</b> yozing (ixtiyoriy):",
        'no_payments': "💳 Hali to'lovlar amalga oshirilmagan.",
        'undo_ok': "↩️ Oxirgi amal bekor qilindi!",
        'undo_empty': "❌ Bekor qilinadigan amal topilmadi.",
        'months': ['Yan', 'Fev', 'Mar', 'Apr', 'May', 'Iyn', 'Iyl', 'Avg', 'Sen', 'Okt', 'Noy', 'Dek'],
        'start_private_title': "🏦 <b>QARZ HISOBCHI BOT</b>",
        'start_private_hint': "👇 Pastdagi tugmalar yoki tezkor yozish: <code>Ism 500000 qarz</code>",
        'start_group_title': "👋 <b>Salom, {title}!</b>",
        'start_group_hint': "🏦 Bot faol. Misol: <code>Alisher 500000 qarz</code> · <code>Alisher 200000 berdi</code>",
        'help_title': "❓ <b>YORDAM</b>",
        'err_internal': "❌ Ichki xato. Keyinroq urinib ko'ring.",
        'list_empty_hint': "➕ tugma yoki <code>Ism summa qarz</code>",
        'reminder_title': "⏰ <b>ESLATMA</b> (har {days} kun)",
        'reminder_active': "👥 {n} ta aktiv qarz:",
        'reminder_overdue': "\n\n⚠️ <b>Muddati o'tgan: {m} ta!</b> /muddat",
        'panel_title': "📱 <b>Tezkor panel</b>",
        'panel_hint': "Quyidagi tugmalar:",
        'btn_list': "📋 Ro'yxat",
        'btn_stats': "📊 Statistika",
        'btn_excel': "📥 Excel",
        'btn_chart': "📅 Grafik",
        'btn_refresh': "🔄 Yangilash",
        'audit_title': "📜 <b>Oxirgi amallar</b> (audit)",
        'audit_empty': "📭 Yozuvlar yo'q.",
        'notify_ok': "✅ Eslatma intervali: <b>{days}</b> kun.",
        'notify_bad': "❌ 1–365 orasida raqam kiriting: <code>/eslatmakun 7</code>",
        'notify_cur': "📅 Hozirgi interval: <b>{days}</b> kun.",
        'bonus_ok': "✅ Muddatdan oldin to'lov bonusi: <b>{pct}%</b> (0 = o'chirilgan).",
        'bonus_bad': "❌ 0–50 orasida: <code>/bonus 5</code>",
        'kurs_title': "💱 <b>Kurslar</b> (.env)",
        'kurs_empty': "RATE_USD_UZS yoki RATE_RUB_UZS o'rnatilmagan.",
        'rate_footer': "\n<i>Taxminiy UZS — rasmiy emas</i>",
        'early_bonus_line': "🎁 Muddatgacha bonus: <b>+{pct}%</b> (effektiv: <b>{eff}</b>)",
        'miniapp_btn': "📱 Mini-panel",
        'reply_linked': "🔗 Xabarga bog'landi (reply).",
        'webhook_mode': "🌐 Webhook rejimi.",
        'polling_mode': "📡 Polling rejimi.",
    },
    'ru': {
        'lang_changed': "✅ Язык: Русский 🇷🇺",
        'no_debts': "📭 Активных долгов нет!",
        'cancelled': "↩️ Отменено.",
        'enter_name': "👤 Введите <b>имя</b> должника:",
        'enter_amount': "💰 Введите <b>сумму</b>:",
        'enter_currency': "💱 Выберите <b>валюту</b>:",
        'enter_category': "🗂 Выберите <b>категорию</b>:",
        'enter_due': "📅 Введите <b>срок</b> (необязательно):",
        'enter_note': "📝 Введите <b>примечание</b> (необязательно):",
        'no_payments': "💳 Платежей ещё не было.",
        'undo_ok': "↩️ Последнее действие отменено!",
        'undo_empty': "❌ Нет действий для отмены.",
        'months': ['Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн', 'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек'],
        'start_private_title': "🏦 <b>БОТ УЧЁТА ДОЛГОВ</b>",
        'start_private_hint': "👇 Кнопки или быстрый ввод: <code>Имя 500000 долг</code>",
        'start_group_title': "👋 <b>Привет, {title}!</b>",
        'start_group_hint': "🏦 Бот активен. Пример: <code>Алишер 500000 долг</code>",
        'help_title': "❓ <b>СПРАВКА</b>",
        'err_internal': "❌ Внутренняя ошибка. Попробуйте позже.",
        'list_empty_hint': "Кнопка ➕ или <code>Имя сумма долг</code>",
        'reminder_title': "⏰ <b>НАПОМИНАНИЕ</b> (каждые {days} дн.)",
        'reminder_active': "👥 {n} активных долгов:",
        'reminder_overdue': "\n\n⚠️ <b>Просрочено: {m}!</b> /muddat",
        'panel_title': "📱 <b>Панель</b>",
        'panel_hint': "Кнопки:",
        'btn_list': "📋 Список",
        'btn_stats': "📊 Статистика",
        'btn_excel': "📥 Excel",
        'btn_chart': "📅 График",
        'btn_refresh': "🔄 Обновить",
        'audit_title': "📜 <b>Последние действия</b>",
        'audit_empty': "📭 Пусто.",
        'notify_ok': "✅ Интервал напоминаний: <b>{days}</b> дн.",
        'notify_bad': "❌ Число 1–365: <code>/eslatmakun 7</code>",
        'notify_cur': "📅 Сейчас: <b>{days}</b> дн.",
        'bonus_ok': "✅ Бонус за досрочный платёж: <b>{pct}%</b> (0 = выкл).",
        'bonus_bad': "❌ 0–50: <code>/bonus 5</code>",
        'kurs_title': "💱 <b>Курсы</b> (.env)",
        'kurs_empty': "RATE_USD_UZS / RATE_RUB_UZS не заданы.",
        'rate_footer': "\n<i>Приблизительно в UZS</i>",
        'early_bonus_line': "🎁 Бонус: <b>+{pct}%</b> (эффективно: <b>{eff}</b>)",
        'miniapp_btn': "📱 Мини-панель",
        'reply_linked': "🔗 Ответ на сообщение сохранён.",
        'webhook_mode': "🌐 Режим webhook.",
        'polling_mode': "📡 Режим polling.",
    },
    'en': {
        'lang_changed': "✅ Language: English 🇺🇸",
        'no_debts': "📭 No active debts!",
        'cancelled': "↩️ Cancelled.",
        'enter_name': "👤 Enter debtor's <b>name</b>:",
        'enter_amount': "💰 Enter the <b>amount</b>:",
        'enter_currency': "💱 Select <b>currency</b>:",
        'enter_category': "🗂 Select <b>category</b>:",
        'enter_due': "📅 Enter <b>due date</b> (optional):",
        'enter_note': "📝 Enter a <b>note</b> (optional):",
        'no_payments': "💳 No payments made yet.",
        'undo_ok': "↩️ Last action undone!",
        'undo_empty': "❌ Nothing to undo.",
        'months': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
        'start_private_title': "🏦 <b>DEBT TRACKER BOT</b>",
        'start_private_hint': "👇 Buttons or quick text: <code>Name 500000 debt</code>",
        'start_group_title': "👋 <b>Hello, {title}!</b>",
        'start_group_hint': "🏦 Bot active. Example: <code>John 500 debt</code>",
        'help_title': "❓ <b>HELP</b>",
        'err_internal': "❌ Internal error. Try again later.",
        'list_empty_hint': "➕ button or <code>Name amount debt</code>",
        'reminder_title': "⏰ <b>REMINDER</b> (every {days} days)",
        'reminder_active': "👥 {n} active debts:",
        'reminder_overdue': "\n\n⚠️ <b>Overdue: {m}!</b> /muddat",
        'panel_title': "📱 <b>Quick panel</b>",
        'panel_hint': "Actions:",
        'btn_list': "📋 List",
        'btn_stats': "📊 Stats",
        'btn_excel': "📥 Excel",
        'btn_chart': "📅 Chart",
        'btn_refresh': "🔄 Refresh",
        'audit_title': "📜 <b>Recent actions</b>",
        'audit_empty': "📭 No entries.",
        'notify_ok': "✅ Reminder interval: <b>{days}</b> days.",
        'notify_bad': "❌ Use 1–365: <code>/eslatmakun 7</code>",
        'notify_cur': "📅 Current interval: <b>{days}</b> days.",
        'bonus_ok': "✅ Early payment bonus: <b>{pct}%</b> (0 = off).",
        'bonus_bad': "❌ Use 0–50: <code>/bonus 5</code>",
        'kurs_title': "💱 <b>Rates</b> (.env)",
        'kurs_empty': "RATE_USD_UZS / RATE_RUB_UZS not set.",
        'rate_footer': "\n<i>Approximate UZS</i>",
        'early_bonus_line': "🎁 Early bonus <b>+{pct}%</b> (effective: <b>{eff}</b>)",
        'miniapp_btn': "📱 Mini panel",
        'reply_linked': "🔗 Linked as reply to message.",
        'webhook_mode': "🌐 Webhook mode.",
        'polling_mode': "📡 Polling mode.",
    },
}

LANGS = _KEYS


def T(chat_id, key, db=None, **kwargs):
    lang = 'uz'
    if db:
        lang = db.get_setting(chat_id, 'lang', 'uz') or 'uz'
    d = LANGS.get(lang, LANGS['uz'])
    text = d.get(key, LANGS['uz'].get(key, key))
    return text.format(**kwargs) if kwargs else text
